### ISSUE TITLE
Consider a new name

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/bulletins#18]
@bboulesteix suggested:
- Epigram
- Paperolles
- Bulletins
- Turbo Retro

**Comment by bzg** [comment]
A few other suggestions:

- Sisyphe
- Danaide
- Spoonful (of Sugar - see Mary Poppins' song)
- Carrousel (or merry-go-round)
- Roundabout (too political ?)

And one of my favorites:

- Goodnews

**Comment by CarineSto** [comment]
- what's up
- what's new
- it's friday !
