### ISSUE TITLE
Priorité / Jalon

### ISSUE THREAD

**Issue by jbledevehat** [entrepreneur-interet-general/bulletins#34]
J'ajouterai bien une date ou des dates potentielles de jalons (sur les mois à venir). Je dirai qu'il faut max 1 ou 2 jalons par mois. Et cette idée me vient, suite à la possibilité grosse priorité (long termiste) qui peut être là même sur plusieurs semaines. Et aussi pour ne pas être focus sur le slot/l'échantillonnage hebdomadaire. 

Bref je vois juste un champs date avec un champs descriptif. Et à voir dans la mesure du possible pour le récupérer d'une semaine à l'autre.

**Comment by AntoineAugusti** [comment]
Done in the mentioned PRs
