### ISSUE TITLE
Compile needs in Slack channel #help

### ISSUE THREAD

**Issue by jbledevehat** [entrepreneur-interet-general/bulletins#44]

**Comment by AntoineAugusti** [comment]
We already have a #help channel on Slack, why don't people use it before filling the form?
Could it be just putting needs at the beginning of the email recap?

If we decide to do this feature:
- When should we post it?
- What should it look like?

**Comment by jbledevehat** [comment]
Why ? 
>>Because people don't have the reflex. And maybe in the end the reflex will be taken. In the long run, maybe this field will no longer be useful.

When ? What ?
>> Juste before the mail, around 15h06 😄 
>> Like this : "#projet-xxx : {message}"

**Comment by AntoineAugusti** [comment]
Could it be just putting needs at the beginning of the email recap?

This way they'll not be buried in the middle.

**Comment by AntoineAugusti** [comment]
I imagined a section dedicated to needs before the current content. Putting needs at the very beginning of the email and then other stuff

**Comment by AntoineAugusti** [comment]
I've tried putting help requests at the beginning of the weekly email.

Let's see if it's enough.
![](https://puu.sh/D2lsJ/3867256e66.png)

cc @soizicpenicaud

**Comment by jbledevehat** [comment]
Ok let's try

**Comment by AntoineAugusti** [comment]
Help requests haven't been used a lot and we've relayed them on Slack when needed. Closing for now.
