### ISSUE TITLE
Allow editing after validation

### ISSUE THREAD

**Issue by jbledevehat** [entrepreneur-interet-general/bulletins#54]

**Comment by AntoineAugusti** [comment]
How should this feature work?

**Comment by jbledevehat** [comment]
I will add a button here : https://www.awesomescreenshot.com/image/3940012/cc2af69b97a6241675fcfedf7fffb15e
And I'll go to the page edition

**Comment by AntoineAugusti** [comment]
Only for the latest week? All weeks?

We don't have a strong authentication system for now. It would mean that anyone would be able to edit all previous reports. This may not be acceptable.

**Comment by jbledevehat** [comment]
Only for the latest week. And we have a password on the "Access to balance sheet history". Is not that enough?

**Comment by AntoineAugusti** [comment]
Instead of a validation system: add a confirmation step. Show what people entered. Give the possibility to confirm or edit.

**Comment by AntoineAugusti** [comment]
Worked on a preview in this PR #138. Hopefully it'll be better
